In [1]:
!pip install imbalanced-learn

In [2]:
import pandas as pd
df1 = pd.read_csv("student-scores-2.csv")
df = df1.copy()
df.head()

id first_name last_name                              email  gender  \
0   1    Sumaiya     Hasan  sumaiya.hasan.1@gslingacademy.com  Female   
1   2        Mim      Alam       mim.alam.2@gslingacademy.com  Female   
2   3      Fahim      Khan     fahim.khan.3@gslingacademy.com    Male   
3   4       Rafi     Islam     rafi.islam.4@gslingacademy.com    Male   
4   5    Tamanna     Kabir  tamanna.kabir.5@gslingacademy.com  Female   

   extracurricular_activities  weekly_self_study_hours     career_aspiration  \
0                        True                       45                Doctor   
1                        True                       31  Software Engineering   
2                        True                       28                 Civil   
3                        True                       44            Biomedical   
4                       False                       22                Lawyer   

   math_score  history_score  physics_score  chemistry_score  biology_score  \
0          90             72             93               90             85   
1          90             74             94               79             88   
2          91             80             79               89             96   
3          78             80             79               83             76   
4          68             82             82               87             80   

   english_score  
0             87  
1             82  
2             81  
3             90  
4             79

Load dataset

create new column from all score

In [3]:
df["total_score"] = df["math_score"] + df["history_score"] + df["physics_score"] + df["chemistry_score"] + df["biology_score"] + df["english_score"] 
df["average_score"] = df["total_score"] / 6
df.head()

id first_name last_name                              email  gender  \
0   1    Sumaiya     Hasan  sumaiya.hasan.1@gslingacademy.com  Female   
1   2        Mim      Alam       mim.alam.2@gslingacademy.com  Female   
2   3      Fahim      Khan     fahim.khan.3@gslingacademy.com    Male   
3   4       Rafi     Islam     rafi.islam.4@gslingacademy.com    Male   
4   5    Tamanna     Kabir  tamanna.kabir.5@gslingacademy.com  Female   

   extracurricular_activities  weekly_self_study_hours     career_aspiration  \
0                        True                       45                Doctor   
1                        True                       31  Software Engineering   
2                        True                       28                 Civil   
3                        True                       44            Biomedical   
4                       False                       22                Lawyer   

   math_score  history_score  physics_score  chemistry_score  biology_score  \
0          90             72             93               90             85   
1          90             74             94               79             88   
2          91             80             79               89             96   
3          78             80             79               83             76   
4          68             82             82               87             80   

   english_score  total_score  average_score  
0             87          517      86.166667  
1             82          507      84.500000  
2             81          516      86.000000  
3             90          486      81.000000  
4             79          478      79.666667

drop irrelevant columns

In [4]:
df.columns
df.drop(columns=['id','first_name','last_name','email'],axis=1, inplace=True)

Encoding Categorical Columns

In [5]:
# from sklearn.preprocessing import LabelEncoder

# # Create a LabelEncoder object
# label_encoder = LabelEncoder()

# # Encode categorical columns using label encoder
# df['gender'] = label_encoder.fit_transform(df['gender'])
# df['part_time_job'] = label_encoder.fit_transform(df['part_time_job'])
# df['extracurricular_activities'] = label_encoder.fit_transform(df['extracurricular_activities'])
# df['career_aspiration'] = label_encoder.fit_transform(df['career_aspiration'])
# Define mapping dictionaries for categorical features
gender_map = {'Male': 0, 'Female': 1}
#part_time_job_map = {False: 0, True: 1}
extracurricular_activities_map = {False: 0, True: 1}
career_aspiration_map = {
        'Lawyer': 0, 'Doctor': 1, 'Civil': 2, 'Biotechnology': 3, 'Software Engineering': 4, 'Biomedical':5}
# Apply mapping to the DataFrame
df['gender'] = df['gender'].map(gender_map)
#df['part_time_job'] = df['part_time_job'].map(part_time_job_map)
df['extracurricular_activities'] = df['extracurricular_activities'].map(extracurricular_activities_map)
df['career_aspiration'] = df['career_aspiration'].map(career_aspiration_map)

In [6]:
df.head()

gender  extracurricular_activities  weekly_self_study_hours  \
0       1                           1                       45   
1       1                           1                       31   
2       0                           1                       28   
3       0                           1                       44   
4       1                           0                       22   

   career_aspiration  math_score  history_score  physics_score  \
0                  1          90             72             93   
1                  4          90             74             94   
2                  2          91             80             79   
3                  5          78             80             79   
4                  0          68             82             82   

   chemistry_score  biology_score  english_score  total_score  average_score  
0               90             85             87          517      86.166667  
1               79             88             82          507      84.500000  
2               89             96             81          516      86.000000  
3               83             76             90          486      81.000000  
4               87             80             79          478      79.666667

In [7]:
df

gender  extracurricular_activities  weekly_self_study_hours  \
0          1                           1                       45   
1          1                           1                       31   
2          0                           1                       28   
3          0                           1                       44   
4          1                           0                       22   
...      ...                         ...                      ...   
4995       0                           0                       44   
4996       1                           0                       32   
4997       1                           0                       27   
4998       1                           0                       31   
4999       0                           0                       23   

      career_aspiration  math_score  history_score  physics_score  \
0                     1          90             72             93   
1                     4          90             74             94   
2                     2          91             80             79   
3                     5          78             80             79   
4                     0          68             82             82   
...                 ...         ...            ...            ...   
4995                  5          78             68             79   
4996                  0          68             82             79   
4997                  4          88             77             82   
4998                  2          97             65             93   
4999                  0          87             93             78   

      chemistry_score  biology_score  english_score  total_score  \
0                  90             85             87          517   
1                  79             88             82          507   
2                  89             96             81          516   
3                  83             76             90          486   
4                  87             80             79          478   
...               ...            ...            ...          ...   
4995               89             97             81          492   
4996               83             80             90          482   
4997               87             80             79          493   
4998               85             88             80          508   
4999               80             80             89          507   

      average_score  
0         86.166667  
1         84.500000  
2         86.000000  
3         81.000000  
4         79.666667  
...             ...  
4995      82.000000  
4996      80.333333  
4997      82.166667  
4998      84.666667  
4999      84.500000  

[5000 rows x 12 columns]

Balance Dataset

In [8]:
df['career_aspiration'].unique()

array([1, 4, 2, 5, 0, 3], dtype=int64)

In [9]:
df['career_aspiration'].value_counts()

career_aspiration
2    1033
0    1030
1     894
3     812
4     638
5     593
Name: count, dtype: int64

Check Installed Versions

In [10]:
from imblearn.over_sampling import SMOTE

# Create SMOTE object
smote = SMOTE(random_state=42)

# Separate features and target variable
X = df.drop('career_aspiration', axis=1)
y = df['career_aspiration']

# Apply SMOTE to the data
X_resampled, y_resampled = smote.fit_resample(X, y)


In [11]:
y_resampled.value_counts()

career_aspiration
1    1033
4    1033
2    1033
5    1033
0    1033
3    1033
Name: count, dtype: int64

Train test Split

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_resampled,y_resampled,test_size=0.2, random_state=42)

In [13]:
X_train.shape

(4958, 11)

Feature Scalling

In [14]:
from imblearn.over_sampling import SMOTE

# Create SMOTE object
smote = SMOTE(random_state=42)

# Separate features and target variable
X = df.drop('career_aspiration', axis=1)
y = df['career_aspiration']

# Apply SMOTE to the data
X_resampled, y_resampled = smote.fit_resample(X, y)

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_resampled,y_resampled,test_size=0.2, random_state=42)
# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler to the training data and transform both training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [15]:
X_train_scaled.shape

(4958, 11)

Models Training (Multiple Models)

In [16]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
#from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")

# Define models
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Classifier": SVC(),
    "Random Forest Classifier": RandomForestClassifier(),
    "K Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Gaussian Naive Bayes": GaussianNB(),
    "AdaBoost Classifier": AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    #"XGBoost Classifier": XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
}

# Train and evaluate each model
for name, model in models.items():
    print("="*50)
    print("Model:", name)
    # Train the model
    model.fit(X_train_scaled, y_train)
    
    # Predict on test set
    y_pred = model.predict(X_test_scaled)
    
    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    # Print metrics
    print("Accuracy:", accuracy)
    print("Classification Report:\n", classification_rep)
    print("Confusion Matrix:\n", conf_matrix)


Model: Logistic Regression
Accuracy: 0.7040322580645161
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.98      0.97       214
           1       0.63      0.76      0.69       203
           2       0.63      0.75      0.69       195
           3       0.64      0.43      0.51       209
           4       0.64      0.57      0.60       206
           5       0.70      0.73      0.72       213

    accuracy                           0.70      1240
   macro avg       0.70      0.70      0.70      1240
weighted avg       0.70      0.70      0.70      1240

Confusion Matrix:
 [[209   0   3   2   0   0]
 [  0 154   0  16   0  33]
 [  4   0 147   2  39   3]
 [  0  59   3  90  26  31]
 [  5   0  79   5 117   0]
 [  0  31   0  26   0 156]]
Model: Support Vector Classifier
Accuracy: 0.9419354838709677
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      0.99       214


Model Selection (Random Forest)

In [17]:
model = RandomForestClassifier()

model.fit(X_train_scaled, y_train)
# Predict on test set
y_pred = model.predict(X_test_scaled)

# Calculate metrics
print("Accuracy: ",accuracy_score(y_test, y_pred))
print("Report:\n",classification_report(y_test, y_pred))
print("Confusion Matrix: \n",confusion_matrix(y_test, y_pred))

Accuracy:  1.0
Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       214
           1       1.00      1.00      1.00       203
           2       1.00      1.00      1.00       195
           3       1.00      1.00      1.00       209
           4       1.00      1.00      1.00       206
           5       1.00      1.00      1.00       213

    accuracy                           1.00      1240
   macro avg       1.00      1.00      1.00      1240
weighted avg       1.00      1.00      1.00      1240

Confusion Matrix: 
 [[214   0   0   0   0   0]
 [  0 203   0   0   0   0]
 [  0   0 195   0   0   0]
 [  0   0   0 209   0   0]
 [  0   0   0   0 206   0]
 [  0   0   0   0   0 213]]


Single Input Predictions

In [18]:
# test 1
print("Actual Label :", y_test.iloc[10])
print("Model Prediction :",model.predict(X_test_scaled[10].reshape(1,-1))[0])
if y_test.iloc[10]==model.predict(X_test_scaled[10].reshape(1,-1)):
    print("Wow! Model doing well.....")
else:
    print("not sure......")

Actual Label : 5
Model Prediction : 5
Wow! Model doing well.....


In [19]:
# test 2
print("Actual Label :", y_test.iloc[300])
print("Model Prediction :",model.predict(X_test_scaled[300].reshape(1,-1))[0])
if y_test.iloc[10]==model.predict(X_test_scaled[10].reshape(1,-1)):
    print("Wow! Model doing well.....")
else:
    print("not sure......")

Actual Label : 2
Model Prediction : 2
Wow! Model doing well.....


In [20]:
# test 3
print("Actual Label :", y_test.iloc[23])
print("Model Prediction :",model.predict(X_test_scaled[23].reshape(1,-1))[0])
if y_test.iloc[10]==model.predict(X_test_scaled[10].reshape(1,-1)):
    print("Wow! Model doing well.....")
else:
    print("not sure......")

Actual Label : 0
Model Prediction : 0
Wow! Model doing well.....


Saving & Load Files

In [21]:
import os

# Create the directory if it doesn't exist
os.makedirs("code", exist_ok=True)  # exist_ok avoids errors if the directory already exists

pickle.dump(scaler, open("code/scaler.pkl", 'wb'))
pickle.dump(model, open("code/model.pkl", 'wb'))

NameError: name 'pickle' is not defined

In [ ]:
import pickle

# SAVE FILES
pickle.dump(scaler,open("code/scaler.pkl",'wb'))
pickle.dump(model,open("code/model.pkl",'wb'))

In [ ]:
# Load the scaler, label encoder, and model
scaler = pickle.load(open("code/scaler.pkl", 'rb'))
model = pickle.load(open("code/model.pkl", 'rb'))

Recommendation System

In [ ]:
import pickle
import numpy as np

# Load the scaler, label encoder, model, and class names
scaler = pickle.load(open("code/scaler.pkl", 'rb'))
model = pickle.load(open("code/model.pkl", 'rb'))
class_names = ['Lawyer', 'Doctor', 'Civil', 'Biotechnology', 'Software Engineering', 'biomedical']

def Recommendations(gender,extracurricular_activities,
                    weekly_self_study_hours, math_score, history_score, physics_score,
                    chemistry_score, biology_score, english_score,total_score,average_score):
    
    # Encode categorical variables
    gender_encoded = 1 if gender.lower() == 'female' else 0
    extracurricular_activities_encoded = 1 if extracurricular_activities else 0
    
    # Create feature array
    feature_array = np.array([[gender_encoded, extracurricular_activities_encoded,
                               weekly_self_study_hours, math_score, history_score, physics_score,
                               chemistry_score, biology_score, english_score,total_score,average_score]])
    
    # Scale features
    scaled_features = scaler.transform(feature_array)
    
    # Predict using the model
    probabilities = model.predict_proba(scaled_features)
    
    # Get top five predicted classes along with their probabilities
    top_classes_idx = np.argsort(-probabilities[0])[:4]
    top_classes_names_probs = [(class_names[idx], probabilities[0][idx]) for idx in top_classes_idx]
    
    return top_classes_names_probs

In [ ]:
# Example usage 1
final_recommendations = Recommendations(gender='female',
                            
                                        extracurricular_activities=False,
                                        weekly_self_study_hours=34,
                                        math_score=97,
                                        history_score=73,
                                        physics_score=83,
                                        chemistry_score=94,
                                        biology_score=95,
                                        english_score=86,
                                    
                                        total_score=583,
                                        average_score=83.285714)

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")


In [ ]:
# Example usage 2
final_recommendations = Recommendations(gender='female',
                                        extracurricular_activities=False,
                                        weekly_self_study_hours=34,
                                        math_score=87,
                                        history_score=93,
                                        physics_score=73,
                                        chemistry_score=74,
                                        biology_score=69,
                                        english_score=96,
                                    
                                        total_score=583,
                                        average_score=83.285714)

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")


In [ ]:
# sklear version in pychar production 
import sklearn
print(sklearn.__version__)
# in pycharm env install
# pip install scikit-learn==1.3.2